version: '3.7'

services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - "80:80"  
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - aplicacao

  mysql:
    container_name: banco
    image: mysql:5.7.30
    networks:
      - aplicacao
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
networks:
  aplicacao:

volumes:
  mysql:
